### ISSUE TITLE
Crashes immediately upon accessing the disk drive.

### ISSUE THREAD

**Issue by TomHarte** [OpenEmulatorProject/OpenEmulator-OSX#20]
Using:
* OpenEmulator 1.0.3;
* macOS 10.13.4.

Steps to reproduce:
Method 1:
1. launch OpenEmulator.
2. using File->New, choose a new Apple II plus.

Method 2:
1. launch OpenEmulator.
2. using File->New, choose a new Apple II.
3. type CTRL+B and enter, to enter integer BASIC.
4. type PR#6 to boot the Disk II.

Sample crash report: [OpenEmulator_2018-04-24-085225_Thomass-MacBook-Air.crash.zip](https://github.com/OpenEmulatorProject/OpenEmulator-OSX/files/1943625/OpenEmulator_2018-04-24-085225_Thomass-MacBook-Air.crash.zip)

**Comment by hoserama99** [comment]
FWIW, I get this too - same crash and backtrace. Makes it pretty much impossible to use the Apple II emulation.

**Comment by zellyn** [comment]
Are you using the version from http://openemulatorproject.github.io/ (which I need to remove) or the version at https://archive.org/details/OpenEmulatorSnapshots (the good one!)?

**Comment by tobier** [comment]
@zellyn I don't see the point of having a snapshot on archive.org when Github supports project websites? It would be better just to keep the github.io site up-to-date.

**Comment by zellyn** [comment]
Pure lazyness. 4am knows how to build it in a way more likely to work for lots of people. I haven't bothered updating the version on github. I need to just make that download link point to archive.org.

**Comment by hoserama99** [comment]
I'm apparently using the bad one from github.io.

**Comment by tobier** [comment]
Should we close this then as it's fixed in newer builds?
